# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(615, 299)
        self.send_file = QtWidgets.QPushButton(Dialog)
        self.send_file.setGeometry(QtCore.QRect(30, 250, 75, 23))
        self.send_file.setObjectName("send_file")
        self.get_file = QtWidgets.QPushButton(Dialog)
        self.get_file.setGeometry(QtCore.QRect(120, 250, 75, 23))
        self.get_file.setObjectName("get_file")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(210, 250, 75, 23))
        self.ok.setObjectName("ok")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(300, 250, 71, 23))
        self.quit.setObjectName("quit")
        self.send_box = QtWidgets.QTextEdit(Dialog)
        self.send_box.setGeometry(QtCore.QRect(30, 40, 321, 21))
        self.send_box.setObjectName("send_box")
        self.send_label = QtWidgets.QLabel(Dialog)
        self.send_label.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.send_label.setObjectName("send_label")
        self.get_label = QtWidgets.QLabel(Dialog)
        self.get_label.setGeometry(QtCore.QRect(30, 80, 71, 21))
        self.get_label.setObjectName("get_label")
        self.get_box = QtWidgets.QTextEdit(Dialog)
        self.get_box.setGeometry(QtCore.QRect(30, 110, 321, 21))
        self.get_box.setObjectName("get_box")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(410, 20, 47, 13))
        self.label.setObjectName("label")
        self.max_chk = QtWidgets.QCheckBox(Dialog)
        self.max_chk.setGeometry(QtCore.QRect(40, 150, 70, 17))
        self.max_chk.setObjectName("max_chk")
        self.hot_chk = QtWidgets.QCheckBox(Dialog)
        self.hot_chk.setGeometry(QtCore.QRect(160, 150, 70, 17))
        self.hot_chk.setObjectName("hot_chk")
        self.back_chk = QtWidgets.QCheckBox(Dialog)
        self.back_chk.setGeometry(QtCore.QRect(280, 150, 70, 17))
        self.back_chk.setObjectName("back_chk")
        self.combo = QtWidgets.QComboBox(Dialog)
        self.combo.setGeometry(QtCore.QRect(410, 250, 151, 22))
        self.combo.setObjectName("combo")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(410, 223, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(400, 280, 191, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 321, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 280, 47, 13))
        self.label_5.setObjectName("label_5")
        self.textBox = QtWidgets.QTextBrowser(Dialog)
        self.textBox.setGeometry(QtCore.QRect(410, 40, 161, 171))
        self.textBox.setObjectName("textBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.send_file.setText(_translate("Dialog", "Send File"))
        self.get_file.setText(_translate("Dialog", "Get File"))
        self.ok.setText(_translate("Dialog", "O K"))
        self.quit.setText(_translate("Dialog", "Quit"))
        self.send_label.setText(_translate("Dialog", "보내는 파일"))
        self.get_label.setText(_translate("Dialog", "받는 파일"))
        self.label.setText(_translate("Dialog", "Process"))
        self.max_chk.setText(_translate("Dialog", "Maximun"))
        self.hot_chk.setText(_translate("Dialog", "Hotspot"))
        self.back_chk.setText(_translate("Dialog", "Back-off"))
        self.combo.setItemText(0, _translate("Dialog", "<밴드를 선택해주세요>"))
        self.combo.setItemText(1, _translate("Dialog", "LTE B2"))
        self.combo.setItemText(2, _translate("Dialog", "LTE B4"))
        self.combo.setItemText(3, _translate("Dialog", "LTE B5"))
        self.combo.setItemText(4, _translate("Dialog", "LTE B7"))
        self.combo.setItemText(5, _translate("Dialog", "LTE B12"))
        self.combo.setItemText(6, _translate("Dialog", "LTE B13"))
        self.combo.setItemText(7, _translate("Dialog", "LTE B14"))
        self.combo.setItemText(8, _translate("Dialog", "LTE B17"))
        self.combo.setItemText(9, _translate("Dialog", "LTE B25"))
        self.combo.setItemText(10, _translate("Dialog", "LTE B26"))
        self.combo.setItemText(11, _translate("Dialog", "LTE B27"))
        self.combo.setItemText(12, _translate("Dialog", "LTE B30"))
        self.combo.setItemText(13, _translate("Dialog", "LTE B38"))
        self.combo.setItemText(14, _translate("Dialog", "LTE B40"))
        self.combo.setItemText(15, _translate("Dialog", "LTE B41_3ch"))
        self.combo.setItemText(16, _translate("Dialog", "LTE B41"))
        self.combo.setItemText(17, _translate("Dialog", "LTE B41(HPUE)"))
        self.combo.setItemText(18, _translate("Dialog", "LTE B41(IC)"))
        self.combo.setItemText(19, _translate("Dialog", "LTE B48"))
        self.combo.setItemText(20, _translate("Dialog", "LTE B66"))
        self.combo.setItemText(21, _translate("Dialog", "LTE B71"))
        self.label_2.setText(_translate("Dialog", "Band 설정"))
        self.label_3.setText(_translate("Dialog", "Design & Developed by 정영환 &박소빈"))
        self.label_4.setText(_translate("Dialog", "***Not Respond가 떠도 종료하지 마세요 작업 중 입니다.***"))
        self.label_5.setText(_translate("Dialog", "ver.1.0.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
